server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezonee=UTC&useSSL=false
    username: khweb
    password: khWeb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
