
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false
    username: khweb
    password: khweb@123
    sdriver-class-name: com.mysql.cj.jdbc.Driver